name: scamandrill
license: https://www.apache.org/licenses/LICENSE-2.0.html
url: https://scamandrill.github.io
baseurl: /scamandrill

github:
  author: dzsessona
  project: scamandrill

source: ./jekyll
markdown: kramdown
highlighter: rouge
